- README.md
- examples/basic/src/cornucopia.rs
- examples/basic/src/main.rs
- src/codegen.rs
- src/container.rs
- src/integration/cornucopia_gen.rs
- src/integration/test.rs
- src/pg_type.rs
> ✨ Rework generated modules namespace.

- Cargo.lock
- Cargo.toml
- src/integration/cornucopia_gen.rs
- src/integration/migrations/1648515058_first.sql
- src/integration/queries/module_2.sql
- src/integration/test.rs
- src/pg_type.rs
- src/read_migrations.rs
- src/run_migrations.rs
Closes #2.
Adds two new types (`MacAddr` and `Inet`).
Adds new tests that verifies *every* supported type works as intended
Also, fixes the CI, since it appears it was just failing silently prior to this PR (lol).
> Feature all the types

- Cargo.lock
- Cargo.toml
- README.md
- examples/basic/Cargo.toml
- examples/basic/src/cornucopia.rs
- examples/basic/src/main.rs
- src/codegen.rs
- src/generic_client.rs
- src/integration/cornucopia_gen.rs
- src/lib.rs
- src/run_migrations.rs
> Feature generic connections

- README.md
- src/cli.rs
- src/container.rs
- src/generic_client.rs
- src/integration/test.rs
- src/lib.rs
> Feature podman

- README.md
- examples/basic/README.md
- src/cli.rs
- src/error.rs
- src/integration/test.rs
- src/lib.rs
- src/pool.rs
> Feature live db

- README.md
- examples/basic/migrations/1648515058_first.sql
- examples/basic/queries/module_1.sql
- examples/basic/queries/module_2.sql
- examples/basic/src/cornucopia.rs
- examples/basic/src/main.rs
- src/codegen.rs
- src/integration.rs
- src/integration/cornucopia.rs
- src/integration/migrations/1648515058_first.sql
- src/integration/migrations/1648515066_second.sql
- src/integration/test.rs
- src/pg_type.rs
> Feature: array types.

- src/codegen.rs
- src/integration/queries/module_2.sql
- src/parse.rs
- src/parse_file.rs
- src/prepare_queries.rs
- src/read_migrations.rs
- src/read_queries.rs
- src/run_migrations.rs
- src/sanitize.rs
> ✨ Improve user-facing error messages.

- Cargo.lock
- Cargo.toml
- README.md
- examples/auto_build/Cargo.toml
- examples/basic/Cargo.toml
> ⬆️ Upgrade dependencies.

- Cargo.lock
- Cargo.toml
- README.md
- examples/auto_build/src/cornucopia.rs
- examples/auto_build/src/main.rs
- examples/basic/src/cornucopia.rs
- examples/basic/src/main.rs
- src/cli.rs
- src/codegen.rs
- src/error.rs
- src/integration.rs
- src/integration/cornucopia.rs
> 54 replace rustfmt by prettyplease

- Cargo.lock
- Cargo.toml
- README.md
- examples/auto_build/Cargo.toml
- src/cli.rs
- src/codegen.rs
- src/conn.rs
- src/container.rs
- src/error.rs
- src/lib.rs
- src/main.rs
- src/prepare_queries.rs
- src/read_migrations.rs
- src/read_queries.rs
- src/run_migrations.rs
Closes #55 .
@Virgiel Do you think more works need to be done to make it compatible with your other PRs? Right now since this is built off of main, it still uses the old async stuff.
> 55 expose a library equivalent to the cli

- .github/workflows/ci.yaml
- Cargo.lock
- Cargo.toml
- examples/auto_build/Cargo.toml
- examples/auto_build/build.rs
- examples/auto_build/src/cornucopia.rs
- examples/basic_sync/Cargo.toml
- examples/basic_sync/migrations/1648515058_first.sql
- examples/basic_sync/migrations/1648515066_second.sql
- examples/basic_sync/queries/module_1.sql
- examples/basic_sync/queries/module_2.sql
- examples/basic_sync/src/cornucopia.rs
- examples/basic_sync/src/main.rs
- integration/Cargo.toml
- integration/fixtures/migration.toml
- integration/fixtures/parser.toml
- integration/fixtures/prepare.toml
- integration/fixtures/validation.toml
- integration/src/main.rs
The test runner is a separate binary that can be run as a CLI with formatted colored output or as a cargo unit test. Two types of tests are available, error tests that check that errors are caught and return a well-formatted message, and example tests that check that all the examples work. 
Error tests are described in TOML files:
```toml
[[test]]
name = 'ColumnNameAlreadyTaken'
query = '''
--! items
SELECT name, price AS name FROM item;
'''
migration = '''
CREATE TABLE item (
name TEXT,
price INTEGER
);
'''
error = '''
Error while preparing query "items" [file: "queries/module_1.sql", line: 1]:
Two or more columns have the same name: `name`. Consider disambiguing the column names with `AS` clauses.'''
```
Closes #60
> Test suite

- .github/workflows/ci.yaml
- src/lib.rs
> 75 enable ci caching

- Cargo.lock
- codegen_test/Cargo.toml
- codegen_test/src/cornucopia_async.rs
- codegen_test/src/cornucopia_sync.rs
- codegen_test/src/main.rs
- cornucopia_client/Cargo.toml
- cornucopia_client/src/lib.rs
- examples/auto_build/build.rs
- integration/src/main.rs
- src/cli.rs
- src/codegen.rs
- src/lib.rs
- src/type_registrar.rs
Adds a `serialize` flag that derives `serde`'s `Serialize` on owned generated items.
> 72 support for #[derive(Serialize)]

- Cargo.lock
- codegen_test/migrations/1648515058_domain.sql
- codegen_test/migrations/1648515058_named.sql
- codegen_test/migrations/1648515058_nullity.sql
- codegen_test/queries/domain.sql
- codegen_test/queries/named.sql
- codegen_test/queries/nullity.sql
- codegen_test/queries/syntax.sql
- codegen_test/src/cornucopia_async.rs
- codegen_test/src/cornucopia_sync.rs
- codegen_test/src/main.rs
- cornucopia_client/src/array_iterator.rs
- cornucopia_client/src/private.rs
- src/codegen.rs
- src/parser.rs
- src/prepare_queries.rs
- src/type_registrar.rs
- src/validation.rs
Support for internal nullity for array values and database types.
Close #65
> Null everywhere

- Cargo.lock
- Cargo.toml
- codegen_test/src/cornucopia_async.rs
- codegen_test/src/cornucopia_sync.rs
- examples/auto_build/src/cornucopia.rs
- examples/basic/src/cornucopia.rs
- examples/basic_sync/src/cornucopia.rs
- src/cli.rs
- src/codegen.rs
- src/error.rs
- src/lib.rs
- src/main.rs
> No code formatting

- codegen_test/queries/syntax.sql
- codegen_test/src/cornucopia_async.rs
- codegen_test/src/cornucopia_sync.rs
- src/parser.rs
Allow `--: Type` instead of `--: Type()`
> Better syntax

- Cargo.lock
- codegen_test/src/cornucopia_async.rs
- codegen_test/src/cornucopia_sync.rs
- codegen_test/src/main.rs
- cornucopia_client/Cargo.toml
- cornucopia_client/src/async_.rs
- cornucopia_client/src/deadpool.rs
- cornucopia_client/src/lib.rs
- examples/auto_build/src/cornucopia.rs
- examples/auto_build/src/main.rs
- examples/basic/src/cornucopia.rs
- examples/basic/src/main.rs
- examples/basic_sync/src/cornucopia.rs
- examples/basic_sync/src/main.rs
- integration/src/main.rs
- src/codegen.rs
The complexity of code generation increases a lot, and we have to do some acrobatics to handle async, but it works
> Statement API

- integration/fixtures/errors/migration.toml
- integration/fixtures/errors/prepare.toml
- integration/fixtures/errors/validation.toml
- integration/src/main.rs
- src/conn.rs
- src/container.rs
- src/error.rs
- src/parser.rs
- src/prepare_queries.rs
- src/read_migrations.rs
- src/run_migrations.rs
- src/type_registrar.rs
- src/validation.rs
The purpose of this PR is to add new validation checks and errors:
- Multiple declaration of a named type
- Row declaration for execute query
- Use of a named type as Row and Params
In preparation I have:
- disabled the auto build script
- re-enabled formatted errors for integration testing 
- improved the current error format (feedback is welcome)
- simplify parser and validation
> Better error

- bench/benches/cornucopia_benches/generated_async.rs
- bench/benches/cornucopia_benches/generated_sync.rs
- bench/benches/cornucopia_benches/mod.rs
- codegen_test/src/cornucopia_async.rs
- codegen_test/src/cornucopia_sync.rs
- codegen_test/src/main.rs
- cornucopia/src/codegen.rs
- examples/auto_build/src/cornucopia.rs
- examples/auto_build/src/main.rs
- examples/basic_async/src/cornucopia.rs
- examples/basic_async/src/main.rs
- examples/basic_sync/src/cornucopia.rs
- examples/basic_sync/src/main.rs
> Change `vec` to `all` and `stream` to `iter`

- codegen_test/queries/stress.sql
- codegen_test/src/cornucopia_async.rs
- codegen_test/src/cornucopia_sync.rs
- codegen_test/src/main.rs
- cornucopia/src/cli.rs
- cornucopia/src/parser.rs
- cornucopia/src/prepare_queries.rs
- cornucopia/src/validation.rs
- cornucopia_client/src/private.rs
- integration/fixtures/errors/validation.toml
> Support inline named type

- cornucopia/src/validation.rs
Small perf fix. No visible change in performance, but I feel better now.
> Use binary search

- codegen_test/queries/named.sql
- codegen_test/queries/stress.sql
- codegen_test/queries/syntax.sql
- codegen_test/src/cornucopia_async.rs
- codegen_test/src/cornucopia_sync.rs
- cornucopia/src/parser.rs
- cornucopia/src/validation.rs
- integration/fixtures/errors/codegen.toml
- integration/fixtures/errors/validation.toml
> Apply strict named type syntax and improve many errors

- Cargo.lock
- cornucopia_client/Cargo.toml
> Remove tokio

- cornucopia/src/container.rs
- cornucopia/src/parser.rs
- cornucopia/src/validation.rs
I was working on the train today and docker failed due to an unstable network. I found that our program was hiding the origin of the error and our help message was useless in this case. I simplified the code, and now we print the error message of the command.
> Better container error

- Cargo.lock
- codegen_test/Cargo.toml
- codegen_test/queries/stress.sql
- codegen_test/schema.sql
- codegen_test/src/cornucopia_async.rs
- codegen_test/src/cornucopia_sync.rs
- codegen_test/src/main.rs
- cornucopia/src/type_registrar.rs
Sorry for not adding any unit tests, stressful days. Think of this as a reminder for the time being. It seems to be working though.
> feat: Support NUMERIC to rust_decimal::Decimal

- examples/basic_async/queries/module_2.sql
- examples/basic_async/schema.sql
- examples/basic_async/src/cornucopia.rs
- examples/basic_async/src/main.rs
- examples/basic_sync/queries/module_2.sql
- examples/basic_sync/schema.sql
- examples/basic_sync/src/cornucopia.rs
- examples/basic_sync/src/main.rs
> Overhaul examples.

- Cargo.lock
- bench/Cargo.toml
- clients/async/Cargo.toml
- clients/core/Cargo.toml
- codegen_test/Cargo.toml
- cornucopia/Cargo.toml
- examples/auto_build/Cargo.toml
- examples/basic_async/Cargo.toml
- integration/Cargo.toml
Only major upgrade is clap 4.0
> Upgrade dependencies.

- README.md
#170 
- As given in the above referenced issue, the MSRV version in the documentation needs to be updated.
- The MSRV version has been updated in accordance with the required changes in the above mentioned issue.
> docs(readme): updated the MSRV version

- clients/core/src/array_iterator.rs
- clients/core/src/domain.rs
- codegen_template/src/lib.rs
- cornucopia/src/codegen.rs
- cornucopia/src/load_schema.rs
- cornucopia/src/prepare_queries.rs
- cornucopia/src/read_queries.rs
- cornucopia/src/type_registrar.rs
- integration/src/main.rs
Small code style improvements using nightly clippy
> Code cleanup
